### ISSUE TITLE
Where to put custom code like forms and other php code

### ISSUE THREAD

**Issue by bhulsman** [ekandreas/bladerunner#21]
Great work on this plugin, seems like the only up-to-date Blade implementation for WordPress at the moment. Just one thing that I'm not sure of; you are replacing the normal php templates like single.php with single.blade.php. But where should we put code like custom forms, or other php POST actions and such?

Wouldn't single.php -> Blade->Render('views/single.blade.php') be a more flexible solution?

**Comment by ekandreas** [comment]
Nice idéa! My solution is based not to disturb the theme in common. But this I would like to try as a complementary solution. Do you want me to try or do you want to make a pull request?

**Comment by bhulsman** [comment]
Well I'm not entirely sure how to implement this. It could be that you had a reason for it working the way it does now. So we'd probably need to discus a good way of creating this functionality then. When this is clear I might be able to make a pull request.

What is required?
- For views to be in a separate folder in the theme root directory. Preferably with a default of /views, but changeable via a filter.
- Render function for use in php templates of wordpress (like single.php).
- ... more?

**Comment by ekandreas** [comment]
v1.0.8 added support for helper function "bladerunner". It is defined as global to simplyfy usage inside ordinary template. Take a look at the readme: https://github.com/ekandreas/bladerunner#template-helper
