### ISSUE TITLE
How to extend blade templates?

### ISSUE THREAD

**Issue by philippkuehn** [ekandreas/bladerunner#22]
Hey,

in Laravel it's easy to extend a blade template like this:

```
Blade::extend(function($value)
{
    return preg_replace('/(\s*)@break(\s*)/', '$1<?php break; ?>$2', $value);
});
```

How can I do this with bladerunner? `Blade::extend` or `Illuminate\Support\Facades\Blade::extend` doesn't work for me.

**Comment by ekandreas** [comment]
No, it's just clean Blade right now without extensions to the syntax.
I really want the plugin syntax to be clean but perhaps we could arrange some kind of way to add custom extensions?

**Comment by ekandreas** [comment]
v1.0.9 supports extensions via filter. Just waiting for some tests to run :-)

**Comment by philippkuehn** [comment]
That sounds great!

**Comment by ekandreas** [comment]
Released v1.0.9 with the support of extensions. Please take this as a experimental beta evaluation.
I'm not really comfortable with using filters like explained in the readme.
Perhaps we could make another type of interface to make it easier?
But alright, let's try this!

**Comment by philippkuehn** [comment]
Filters are the WordPress-way to go. So I think that's pretty good. Thank you for your super fast update!

**Comment by ekandreas** [comment]
Perhaps the array added should contain arrays and not key/value. And perhaps with specific parameters:

```
$extensions[] = [
    'pattern'=>'...',
    'replace'=>'...',
];
```

**Comment by hanspagel** [comment]
Nice idea, this would improve the readability in my opinion. Especially with all the regex stuff, keys would become pretty unreadable otherwise.
