### ISSUE TITLE
Fatal error with alternative setup

### ISSUE THREAD

**Issue by seafarer** [ekandreas/bladerunner#28]
This plugin looks awesome but I am getting fatal errors with a non-traditional setup. I am using [bedrock](https://github.com/roots/bedrock) and [trellis](https://github.com/roots/trellis) from [roots](https://github.com/roots). Its a multisite install and uses PHP 7. Here is the error below. I also tried manually creating the cache folder with 777 permissions but it still gave numerous errors. Any thoughts?

Warning: file_exists(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/srv/www/:/tmp) in /srv/www/glenwoodadventure.com/current/web/wp/wp-includes/functions.php on line 1580
Call Stack
# Time    Memory  Function    Location

1   0.0014  472888  {main}( )   .../plugins.php:0
2   0.3870  23429336    do_action( )    .../plugins.php:166
3   0.3870  23431016    Bladerunner\Init::createCacheDirectory( )   .../plugin.php:525
4   0.3873  23431184    wp_mkdir_p( )   .../Init.php:40
5   0.3873  23431184    file_exists ( ) .../functions.php:1580

**Comment by ekandreas** [comment]
Make sure that you have web/app/uploads writable and if needed create the .cache -folder under uploads.
The plan forward is to eliminate the need of file system and make use of flysystems memory files to avoid the troubles with the cache folder.

**Comment by ekandreas** [comment]
You can also put a custom cache folder to the project with the filter "bladerunner/cache/path".
Eg, 

``` php
// Bladerunner filter for custom cache folder, placed in eg, functions.php
add_filter('bladerunner/cache/path', '/srv/www/glenwoodadventure.com/shared/web/app/uploads/.cache');
```

**Comment by seafarer** [comment]
Thanks Andreas. I dont know what happened, but I recreated the folder and deactivated and reactivated the plugin and it started working.

**Comment by ekandreas** [comment]
Ok, great but scary. I have another issue with the same problem and I really should enjoy a better solution than physical file cache...
