### ISSUE TITLE
Trouble passing variables

### ISSUE THREAD

**Issue by seafarer** [ekandreas/bladerunner#31]
I am not understanding how the [template data filter](https://github.com/ekandreas/bladerunner#template-data-filter) works. I have tried just using the sample code in my theme a whole bunch of different ways but it always reports undefined variable. Can you shed any light on how to use this filter properly?

**Comment by seafarer** [comment]
Ok, I got this to output data by using

```
$data = [
    'this'  => 'that',
    'other' => 'perhaps',
];
add_filter('bladerunner/templates/data/single-activity', $data);
```

And then using 

`bladerunner('views.pages.single-activity', compact('data'));`

But I am getting error notices that say "Undefined offset: 0" on the add_filter line above. How can I get rid of that error?

**Comment by ekandreas** [comment]
There is no template filter in that meaning. 
Just deliver the data to the bladerunner function and use it in your blade template.

**Comment by seafarer** [comment]
Ok I got this working. Thanks.

**Comment by ekandreas** [comment]
Great!
