### ISSUE TITLE
Cant find template.

### ISSUE THREAD

**Issue by seafarer** [ekandreas/bladerunner#34]
I am trying to debug a PHP notice, but the template that is throwing the notice is not in the cache. I have cleared the cache and resaved the page a bunch of times but no matter what I do the template does not appear in the cache folder, even though all of the other parts are in there, such as the header, footer etc. The debug tools point to a file that does not seem to exist, even though the page is rendering. Thoughts?

**Comment by ekandreas** [comment]
The WP_DEBUG flag makes the cache removed before render a page. Please try with the flag set to false and make another try!
