### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by bumTomica** [ekandreas/bladerunner#36]
Hello,

I'm trying to pass a variable like this, but I'm getting undefined variable notice. Can you please advise what am I doing wrong.

page-templates\page-home.php

``` php
<?php /* Template Name: Home */

$title = 'Test'

bladerunner('views.pages.home', [
  'title' => $title
]);
```

views\pages\home.blade.php

``` php
@extends('views.layouts.index')

@section('main')

  {{ $title }}

@endsection
```

**Comment by ekandreas** [comment]
Could you please provide me with the version # of Bladerunner?

**Comment by bumTomica** [comment]
1.4.3

It's loaded via Composer as Roots.io must-use plugin. When I remove passing variables everything works as expected.

**Comment by ekandreas** [comment]
Hmm, I have the exact example as you but can't reproduce the error. Are you sure the variable names are exact?

**Comment by ekandreas** [comment]
A semicolon missing at @title = 'Test', perhaps?

**Comment by bumTomica** [comment]
Quick [Screenshot](https://s21.postimg.org/mkyrlpmyf/Blade_WP_error.png)

**Comment by ekandreas** [comment]
Could you empty all files in the folder .cache and try again?

**Comment by ekandreas** [comment]
And it's ok to contact me via Skype. I have added you there in a try to reach you :-)

**Comment by bumTomica** [comment]
It's the same. :( Tried manually and with WP admin. And will do :)

**Comment by ekandreas** [comment]
Having a hard time to reproduce the error. Your example works just fine here, sorry for that.

**Comment by bumTomica** [comment]
Removed plugin, provisioned Trellis, added plugin again, now works as expected. Well that is also a way of fixing problems :D Thanks for help and sorry for inconvenience! :)

**Comment by ekandreas** [comment]
Ok, happy to know that you are moving forward. 
And a reminder, we release the v1.5 of Bladerunner now based on L5.3
