### ISSUE TITLE
Using a laravel database when wordpress is a subfolder

### ISSUE THREAD

**Issue by ghost** [ekandreas/bladerunner#41]
Is there anyway to use the database from the main Laravel application when Wordpress is installed in a subfolder?

i.e., `$users = DB::table('users')->get();`

My structure is like this:

-Laravel
---main app folders
---public
-----blog
-------wp-content
--------plugins
----------bladerunner

**Comment by ekandreas** [comment]
Then you need WP to run inside a Laravel context. You can always force a facade with DB inside WP to catch up the settings from Laravel and run them in that context. I have tried something similar but more of catching the WP-database with Eloquent.
