### ISSUE TITLE
Need A Template Engine for Plugin

### ISSUE THREAD

**Issue by zaingithub** [ekandreas/bladerunner#42]
Hello, can i implement your plugin to create template to make a documentation for the example. Or you can make it globally, so everywhere we can use blade whatever in theme or plugin.

I have using h2o template, to make a dynamic unique post. I render that template on post_content when i try to make wp_insert_post();

if this can handle what i want, it will be very nice :)

Thank you

**Comment by ekandreas** [comment]
The function `bladerunner` or even better the `view` functions are globally defined in the Bladerunner plugin. So you can reach the Blade functions both in themes and plugins.

**Comment by ekandreas** [comment]
Or like this example: 
```
add_filter('bladerunner/template/bladepath', function() {
    return __DIR__.'/views';
});
```
