### ISSUE TITLE
Root folder for referencing views

### ISSUE THREAD

**Issue by bumTomica** [ekandreas/bladerunner#43]
Hello,

It would be nice to have an option to set root folder for all file references. For example my views are stored in resources/views so I need to reference it like @include('resources.views.includes.head').

It would be much nicer if there is an option to set that it starts referencing from resources/views and then I could only do @include('includes.head').

**Comment by ekandreas** [comment]
Have you tried this?
```
add_filter('bladerunner/template/bladepath', function() {
    return __DIR__.'/views';
});
```

**Comment by bumTomica** [comment]
Missed that, thanks! :)
