### ISSUE TITLE
Controllers

### ISSUE THREAD

**Issue by samburgers** [ekandreas/bladerunner#44]
Hi, thanks for publishing this!

Is there any room for scoping Controller functionality similar to this?

https://github.com/soberwp/controller

Cheers!

**Comment by ekandreas** [comment]
Yes! It would be great!

**Comment by bumTomica** [comment]
Any plans on doing it @ekandreas?

**Comment by ekandreas** [comment]
Like this?
https://github.com/soberwp/controller/blob/master/README.md

Med vänlig hälsning, 
Andreas Ek, 070-3032203

**Comment by ekandreas** [comment]
Controller functions will be added in branch develop soon. Now working with gitflow in this repo.

**Comment by ekandreas** [comment]
I would be very glad for feedback to the beta-version with controllers added!

**Comment by samburgers** [comment]
thanks @ekandreas will be using it on our next build coming up very soon! really great stuff :)
