### ISSUE TITLE
Namespace error

### ISSUE THREAD

**Issue by Solinx** [ekandreas/bladerunner#46]
Hi,

Thanks for creating this plugin! Unfortunately I ran into an issue while deploying the website to production:

> PHP Fatal error:  Cannot use Illuminate\\Container\\Container as Container because the name is already in use in .../wp-content/plugins/bladerunner/src/BladeProvider.php on line 4

Unfortunately I'm not precisely sure what caused this, as the code ran fine on my box. However, it was fixed by adding `use Illuminate\Contracts\Container\Container as ContainerContract;` to Container.php 

And by renaming `use Illuminate\Container\Container;` to `use Illuminate\Container\Container as BaseContainer;`, including of course renaming `Container` to `BaseContainer` in the class.

I'm not certain both were required. I was unable to reproduce the error and deployment had to go through someone else, so I just passed on the changes for both suspect issues at the same time.

Cheers,
Wouter

**Comment by ekandreas** [comment]
Yes, it's a challenge to use Laravel components if it's used somewhere else in the application/project.

**Comment by Solinx** [comment]
Hmm... shouldn't the Bladerunner namespace take care of that? Anyway, I'm glad it was so easily fixed. I don't want to think about having to abandon blade templating in exchange for plain WP templating!

**Comment by ekandreas** [comment]
We can try to fix it. Yes, Blade is awesome in WordPress development for templates.

**Comment by ekandreas** [comment]
I have trouble reproducing this error. Can you help me with some steps?

**Comment by ekandreas** [comment]
Version 1.6.3 is on it's way with this merged

**Comment by Solinx** [comment]
Nice! Thanks!

And sorry, I can't. The error only occurred on a production server where for security reasons I only have access to the theme folder and an plain WP editor role. The error does not occur on my development box either. Unfortunately I have no idea which plugins are running on the production server.

All that I do know about it is that this error occurred, that the lack of a ContainerContract reference in Container.php was highlighted as an issue by PHPStorm, and that together with renaming the Container reference this fixed things.

**Comment by ekandreas** [comment]
I got an update from Stefano Vena fixing this and it is merged with version 1.6.3.

Next step now is to create controllers inside Bladerunner <3


Med vänlig hälsning, 
Andreas Ek, 070-3032203
