### ISSUE TITLE
WordPress template hierarchy

### ISSUE THREAD

**Issue by bumTomica** [ekandreas/bladerunner#48]
Is it possible to force WordPress to look for .blade.php files in template hierarchy? For example 404.php in theme root to be able to rename to 404.blade.php, write blade stuff in there and it would magically work? Now you have 404.php with bladerunner or view function and then 404.blade.php with blade stuff. I see that Roots has something like that, and this had it too I guess, not sure why it is removed? A lot of nearly empty .php files just for keeping WordPress happy :(

And also "view" is more Laravel-like name for the blade function call, maybe it should echo by default, and optional parameter for no echo?

**Comment by ekandreas** [comment]
I understand your needs (2 of them here).
The problem with overriding the WordPress templating structure like Roots/Sage is that you have to cover a lot of them and loose some specific and good stuff from WordPress. Eg, translating categories and stuff. Earlier we had the Sage approach but it limits the possibilities. When you create a large theme you don't want that. So we will stick with the overhead of creating entries.

And so to the `view` question. Yes, we copy the functionality from Laravel with the global function `view` and it works just like that, no echo as default. It is good in cases like using it in shortcode-controllers and you should always go for a manual echo. Please use the old `bladerunner` if you would like a more "wordpress" approach with echo as default. Perhaps it´s ok?

**Comment by bumTomica** [comment]
Great, thanks for explanations!

We used bladerunner in couple of WP projects and just observations we had as a team - overhead on please-be-happy-WordPress files (maybe future controllers could be defined in them too), and "echo view('..')" because it is much cleaner call.

**Comment by ekandreas** [comment]
I'm struggling with implementing the Sage Controller from soberwp right now. But I find it ugly and it creates a lot of assumptions. It will be released in a beta soon.

**Comment by ekandreas** [comment]
Controllers added now will make the life easier :-)
Please test and give feedback!
