### ISSUE TITLE
@mysyntax not being substituted

### ISSUE THREAD

**Issue by stevenmunro** [ekandreas/bladerunner#56]
I'm using version 1.7 of the bladerunner plugin in my WordPress installation, which has the composer requirements ( "ekandreas/bladerunner": "*" )

Template files appear to working great - I'm really excited. However when I tried your @mysyntax example, it wasn't being replaced as expected.

I have the following in my functions.php

`add_filter('bladerunner/extend', function($extensions) {`
`    $extensions[] = [`
`        'pattern' => '/(\s*)@mysyntax(\s*)/',`
`        'replace' => '$1<?php echo "MYSYNTAX COMPILED!"; ?>$2',`
`    ];`
`    return $extensions;`
`});`

**Comment by ekandreas** [comment]
Think it's an old feature that is lost when rebuiding the plugin at v1.6 completely from Roots Sage. 
It's a nice feature so let me see if we can add it again. Give me a couple of days and I will come back to you in this issue.

**Comment by stevenmunro** [comment]
Cheers @ekandreas 
I was hoping to create custom post types for blips of content and have these wired up to display dynamically in the blade templates where applicable, so this feature is a start.

**Comment by stevenmunro** [comment]
Hi @ekandreas I'm revisiting this feature, were you able to spend any time on this?

**Comment by stevenmunro** [comment]
Is this feature dead?

**Comment by ekandreas** [comment]
The feature is removed after code rewrite from Sage. 
It would be a nice feature to have but instead of making extension you should use controllers with standard Blade directives. 
Perhaps you could share your challange of what you plan to solve and we could help you with an alternative way?

**Comment by stevenmunro** [comment]
Hi @ekandreas 
I'd like to be able to insert content anywhere in WordPress (using the content editor) and the tag I use includes the content of a specific blade template.

For example, I have a contact form called contact.blade.php and I can insert this contact form anywhere in my site simply by typing '@contact' (or similar)

**Comment by ekandreas** [comment]
Ahh, some kind of shortcode feature coupled to a blade template? Perhaps even better to couple it to a controller fetching arguments. 
But you need to transform db-content to code. Better to use shortcodes for that?


Med vänlig hälsning, Andreas Ek, 070-3032203

**Comment by stevenmunro** [comment]
Yes, in fact something like this would be extremely useful.

I can deal with shortcode, but I would have no idea where to begin with the controller fetching stuff.

**Comment by ekandreas** [comment]
You dont have to. Just create a shortcode that returns a view. 


Med vänlig hälsning, Andreas Ek, 070-3032203

**Comment by stevenmunro** [comment]
@ekandreas 

Would you be so kind to provide a quick example of the controller returning a view? I'm start on this part.

**Comment by ekandreas** [comment]
Eg, in functions.php:
```
// anonymous function for shortcode in functions.php
add_shortcode('icon', function($atts, $content) {
    $class=isset($atts['class']) ? $atts['class'] : 'fa-eye';

    return view('views.shortcodes.icon', ['class'=>$class]);
});
```

And an example for the view:
```
<!-- views/shortcodes/icon.blade.php -->
<i class="fa {{ $class }}"></i>
```

**Comment by ekandreas** [comment]
This controller will return a specific view, placed under a folder named "controllers" in the theme:
```
<?php
// {theme-path}/controllers/single.php
namespace YourVendor\YourTheme\controllers;

use Bladerunner\Controller;

class single extends Controller
{
    protected $view = 'views.single-special';
}
```
And it will work if you place a blade template with the name single-special.blade.php under views.
single.blade.php under views is expected but with $view you override the template.

**Comment by stevenmunro** [comment]
Thanks! I'll have a look. Would be cool to have it fail silently if the template didn't exist (like get_template_part does)

**Comment by ekandreas** [comment]
Yes, there will always be things to do in a project like this :-)
