### ISSUE TITLE
Where do I composer require this?

### ISSUE THREAD

**Issue by corysimmons** [ekandreas/bladerunner#57]
Docs aren't clear. I tried to `composer require` this in my WP root and in my theme folder, neither made it show up in my plugins.

**Comment by corysimmons** [comment]
I've also tried it from `wp-content/plugins` to no success.

Upon further inspection, this plugin is:

1. Packaged wrong for WP usage.
2. Not in the WP plugin directory.
3. Docs are severely lacking.

Looks like a pretty cool plugin. Hope these things get fixed.

**Comment by corysimmons** [comment]
http://bladerunner.elseif.se/bladerunner.zip also 404's.

**Comment by ekandreas** [comment]
Yes, we are leaving the ordinary plugin install and focusing on this tool as a developer package / library.
First of all, use a composer based WordPress installation. It's not possible to use composer in a WP root in your case.
Sorry that all documentation not is up to date.
