### ISSUE TITLE
specify view for particular page

### ISSUE THREAD

**Issue by stevenmunro** [ekandreas/bladerunner#62]
In WordPress, you could specify in the page edit screen which page template to use. How would I go about having this option with this plugin?

**Comment by ekandreas** [comment]
Put @controller in the view code and you get some debug info with template hierarchy.

**Comment by stevenmunro** [comment]
> @controller

I did this and I got

`Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Bladerunner\ControllerDebug' not found in /app/public/wp-content/uploads/.cache/fd8b028a44580e18f43362604ca43a0e64f8420e.php on line 13`

**Comment by stevenmunro** [comment]
I don't know what it is specifically, but I disabled PHP-Composer on my WordPress installation, and used the plugin at http://bladerunner.elseif.se/app/uploads/bladerunner.zip instead. That made the error go away.

**Comment by ekandreas** [comment]
The @controller directive came in v1.7 with the controller functions. Perhaps an old Bladerunner version via composer?
