### ISSUE TITLE
bladerunner/cache/permission is ignored

### ISSUE THREAD

**Issue by fiskhandlarn** [ekandreas/bladerunner#64]
https://github.com/ekandreas/bladerunner#filters talks about the filter `bladerunner/cache/permission`, but it seems that filter isn't run at all. Also, I can't find any reference for that (or for "cache") in the repo when searching here on github or in the downloaded package. Please advise.

**Comment by ekandreas** [comment]
Yes, you are on to some old documentations before we migrated to a new codebase from the Sage-approach. I have made a new filter in the latest dev-master. It will get out in 1.7.5 soon.

**Comment by fiskhandlarn** [comment]
Great, thanks! 
Will the rest of the filters in the docs (`bladerunner/cache/make` and `bladerunner/controller/paths`) be working in 1.7.5 too?

**Comment by ekandreas** [comment]
Yes, check out a dev-master and try it. Would be very nice with feedback! Thanks!

**Comment by ekandreas** [comment]
These settings are optional, by the way

**Comment by fiskhandlarn** [comment]
`bladerunner/cache/permission` works with dev-master. Thank you!

**Comment by fiskhandlarn** [comment]
`bladerunner/cache/make` also works.

I'm trying to check `bladerunner/controller/paths` as well. It's being called as far as I can see, but I'm getting the following error when trying this [Controller example](https://github.com/ekandreas/bladerunner#controller-example):

```
Notice: Undefined variable: images in /public/uploads/.cache/9b8a21595a5f81c0f6cc183242395b151001f28f.php on line 1
```

**Comment by fiskhandlarn** [comment]
Should I create a new issue for the Controller problem above?

**Comment by ekandreas** [comment]
Sorry, can´t reproduce the controller error. It works just great.

**Comment by ekandreas** [comment]
Please create another issue if it persists

**Comment by fiskhandlarn** [comment]
@ekandreas I made it work now. I guess I must have tried to include the controller and blade template for single from another wordpress template file before.

Thus `bladerunner/controller/paths` works as expected. Thanks!
