### ISSUE TITLE
bladerunner/cache/path filter not being honored

### ISSUE THREAD

**Issue by nathanaelphilip** [ekandreas/bladerunner#71]
i have this in my theme, but it’s not changing the path to .cache. Am I doing something wrong?

```
add_filter('bladerunner/cache/path', function() {
    return WP_CONTENT_DIR.'/.cache';
  });
```

**Comment by peter-brennan** [comment]
Did you come up with a solution to this. It is not working for me either.

**Comment by vpillinger** [comment]
The issue here is the following:

Version 1.7.4
```
    \Bladerunner\Config::repo([
            'view.compiled' => "{$paths['dir.upload']}/.cache",
            'view.paths' => $viewPaths,
        ] + $paths);
```

Master
```
    \Bladerunner\Config::repo([
            'view.compiled' => apply_filters('bladerunner/cache/path', "{$paths['dir.upload']}/.cache"),
            'view.paths' => \Bladerunner\Config::viewPaths(),
        ] + $paths);
```

So you need to be using the version from the master branch to have this work.

@ekandreas This can be fixed by releasing a new version with the code from the master branch.

**Comment by ekandreas** [comment]
Hi!
This is a deprecated package. Please use https://github.com/EFTEC/BladeOne instead!
