### ISSUE TITLE
website down?

### ISSUE THREAD

**Issue by Pushplaybang** [ekandreas/bladerunner#72]
Seems to be down, see an error in the console for a 404?

**Comment by ekandreas** [comment]
Sorry, it seems like the site is down `http://bladerunner.elseif.se/`
Will take a look on that.

**Comment by nathanaelphilip** [comment]
@ekandreas can you post a version of the distributed plugin? your site is still down.

**Comment by ekandreas** [comment]
We have to inactivate the plugin to get the site publication to work.
It is the latest version used.

Regards, Andreas Ek, +46703032203

**Comment by nathanaelphilip** [comment]
@ekandreas i don’t know what that means – how can i get a zipped version of the distributed plugin?

**Comment by ekandreas** [comment]
To reproduce the bug in your plugin:

1. Switch site from http to https
2. Keep the settings in OneSignal for the same domain, http
3. Download the latest OneSignal WordPress plugin (wpackagist or official repo)
4. Try to publish or change a post => error

Regards, Andreas Ek, +46703032203

**Comment by nathanaelphilip** [comment]
I have no idea what OneSignal is. There is no bug in my plugin – i just need a distributed version of the *BladeRunner* plugin.

**Comment by ekandreas** [comment]
Sorry for mixing issues here.
There is no disitrubution of the plugin no more. You have to compile one yourself.

**Comment by nathanaelphilip** [comment]
@ekandreas ok, thank you. is that just running `composer install` in the directory?

**Comment by ekandreas** [comment]
Yes, correct!

**Comment by ekandreas** [comment]
Hi!
This is a deprecated package. Please use https://github.com/EFTEC/BladeOne instead!
