### ISSUE TITLE
Bundling with the theme, rather than installing as a plugin

### ISSUE THREAD

**Issue by Pushplaybang** [ekandreas/bladerunner#73]
Hi There

As blade would be a hard dependency for a theme, it makes sense to me that as developers we could bundle this with the theme.

Is it currently possible to include the library without "activating it as a plugin" ?  I'm sure some people like this feature, but I'd far prefer to put this into my theme code.

Thanks for the awesome looking library.

**Comment by webstractions** [comment]
@Pushplaybang I don't see why you can't include BladeRunner inside of your theme. Of course, you would be responsible for updating the source on your own afterwards.

If you cloned this repository inside of your theme, ran composer for the dependancies, then `included` the main `bladerunnner.php` plugin file in your theme setup, you should be pretty much good to go.

**Comment by Pushplaybang** [comment]
Cheers, appreciate it, landed up switching to sage9, as I just kept having issues with adding libs into my own theme.
