### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by MaximVanhove** [ekandreas/bladerunner#80]
I get warnings when WP_DEBUG is set to true.

`<b>Warning</b>:  unlink(/site/storage/views/cache/011c6fea2e3983d5b59d52be3c8f6f35b04a139e.php): No such file or directory in <b>/site/public/mu-plugins/bladerunner/globals/setup.php</b> on line <b>55</b><br />`

This could by fixed by using a helper function `unlink_if_exists` 

```
if (!function_exists('unlink_if_exists')) {
    function unlink_if_exists($file)
    {
        return is_file($file) && @unlink($file);
    }
}
```

```
array_map('unlink_if_exists',
    glob(\Bladerunner\Config::repo('view.compiled') . '/*'));
```

**Comment by ekandreas** [comment]
Hi!
This is a deprecated package. Please use https://github.com/EFTEC/BladeOne instead!
