### ISSUE TITLE
Bladerunner only for plugin development

### ISSUE THREAD

**Issue by hermannatz** [ekandreas/bladerunner#83]
Hey folks,
it's possible to use Bladerunner as base template when developing plugins?
Our content team use Elementor for content creation, so I just wandered if Bladerunner could have an impact on Elementor since, we only need a template engine for our plugins
Thank you in advance for your answer.
Sincerely
Hermann

**Comment by ekandreas** [comment]
It is possible but I would go for https://github.com/EFTEC/BladeOne instead as it is active.
This repo isn't active...

**Comment by ekandreas** [comment]
Hi!
This is a deprecated package. Please use https://github.com/EFTEC/BladeOne instead!
