### ISSUE TITLE
Fix PHP 7.3+ Issue

### ISSUE THREAD

**Issue by nathanaelphilip** [ekandreas/bladerunner#84]
I know this plugin isn’t being actively developed, but would you mind checking to see why the plugin crashes on PHP 7.3+? Or at least if I can figure out, would you be able to approve a PR so I don’t have to rewrite a bunch of sites :)

it seems as though the routing gets messed up – i’m trying to debug it a bit more; 
it seems that the Index.php controller is controlling all the page renders. 

Any guidance on how to debug this further would be super helpful! :)

**Comment by ekandreas** [comment]
Hi!
This is a deprecated package. Please use https://github.com/EFTEC/BladeOne instead!
